/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AddRouteImport } from './routes/add'
import { Route as EndingSoonRouteImport } from './routes/ending-soon'
import { Route as RecentRouteImport } from './routes/recent'
import { Route as SearchRouteImport } from './routes/search'
import { Route as EndListIndexRouteImport } from './routes/end-list.index'
import { Route as StoriesIndexRouteImport } from './routes/stories.index'
import { Route as ThingSlugRouteImport } from './routes/thing.$slug'
import { Route as EndListYearMonthRouteImport } from './routes/end-list.$year.$month'
import { Route as StoriesSlugNumRouteImport } from './routes/stories.$slug.$num'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AddRoute = AddRouteImport.update({
  id: '/add',
  path: '/add',
  getParentRoute: () => rootRouteImport,
} as any)
const EndingSoonRoute = EndingSoonRouteImport.update({
  id: '/ending-soon',
  path: '/ending-soon',
  getParentRoute: () => rootRouteImport,
} as any)
const RecentRoute = RecentRouteImport.update({
  id: '/recent',
  path: '/recent',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const EndListIndexRoute = EndListIndexRouteImport.update({
  id: '/end-list/',
  path: '/end-list/',
  getParentRoute: () => rootRouteImport,
} as any)
const StoriesIndexRoute = StoriesIndexRouteImport.update({
  id: '/stories/',
  path: '/stories/',
  getParentRoute: () => rootRouteImport,
} as any)
const ThingSlugRoute = ThingSlugRouteImport.update({
  id: '/thing/$slug',
  path: '/thing/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const EndListYearMonthRoute = EndListYearMonthRouteImport.update({
  id: '/end-list/$year/$month',
  path: '/end-list/$year/$month',
  getParentRoute: () => rootRouteImport,
} as any)
const StoriesSlugNumRoute = StoriesSlugNumRouteImport.update({
  id: '/stories/$slug/$num',
  path: '/stories/$slug/$num',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/add': typeof AddRoute
  '/ending-soon': typeof EndingSoonRoute
  '/recent': typeof RecentRoute
  '/search': typeof SearchRoute
  '/thing/$slug': typeof ThingSlugRoute
  '/end-list/': typeof EndListIndexRoute
  '/stories/': typeof StoriesIndexRoute
  '/end-list/$year/$month': typeof EndListYearMonthRoute
  '/stories/$slug/$num': typeof StoriesSlugNumRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/add': typeof AddRoute
  '/ending-soon': typeof EndingSoonRoute
  '/recent': typeof RecentRoute
  '/search': typeof SearchRoute
  '/thing/$slug': typeof ThingSlugRoute
  '/end-list': typeof EndListIndexRoute
  '/stories': typeof StoriesIndexRoute
  '/end-list/$year/$month': typeof EndListYearMonthRoute
  '/stories/$slug/$num': typeof StoriesSlugNumRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/add': typeof AddRoute
  '/ending-soon': typeof EndingSoonRoute
  '/recent': typeof RecentRoute
  '/search': typeof SearchRoute
  '/thing/$slug': typeof ThingSlugRoute
  '/end-list/': typeof EndListIndexRoute
  '/stories/': typeof StoriesIndexRoute
  '/end-list/$year/$month': typeof EndListYearMonthRoute
  '/stories/$slug/$num': typeof StoriesSlugNumRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/add'
    | '/ending-soon'
    | '/recent'
    | '/search'
    | '/thing/$slug'
    | '/end-list/'
    | '/stories/'
    | '/end-list/$year/$month'
    | '/stories/$slug/$num'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/add'
    | '/ending-soon'
    | '/recent'
    | '/search'
    | '/thing/$slug'
    | '/end-list'
    | '/stories'
    | '/end-list/$year/$month'
    | '/stories/$slug/$num'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/add'
    | '/ending-soon'
    | '/recent'
    | '/search'
    | '/thing/$slug'
    | '/end-list/'
    | '/stories/'
    | '/end-list/$year/$month'
    | '/stories/$slug/$num'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  AddRoute: typeof AddRoute
  EndingSoonRoute: typeof EndingSoonRoute
  RecentRoute: typeof RecentRoute
  SearchRoute: typeof SearchRoute
  ThingSlugRoute: typeof ThingSlugRoute
  EndListIndexRoute: typeof EndListIndexRoute
  StoriesIndexRoute: typeof StoriesIndexRoute
  EndListYearMonthRoute: typeof EndListYearMonthRoute
  StoriesSlugNumRoute: typeof StoriesSlugNumRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add': {
      id: '/add'
      path: '/add'
      fullPath: '/add'
      preLoaderRoute: typeof AddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ending-soon': {
      id: '/ending-soon'
      path: '/ending-soon'
      fullPath: '/ending-soon'
      preLoaderRoute: typeof EndingSoonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recent': {
      id: '/recent'
      path: '/recent'
      fullPath: '/recent'
      preLoaderRoute: typeof RecentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/end-list/': {
      id: '/end-list/'
      path: '/end-list'
      fullPath: '/end-list/'
      preLoaderRoute: typeof EndListIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stories/': {
      id: '/stories/'
      path: '/stories'
      fullPath: '/stories/'
      preLoaderRoute: typeof StoriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thing/$slug': {
      id: '/thing/$slug'
      path: '/thing/$slug'
      fullPath: '/thing/$slug'
      preLoaderRoute: typeof ThingSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/end-list/$year/$month': {
      id: '/end-list/$year/$month'
      path: '/end-list/$year/$month'
      fullPath: '/end-list/$year/$month'
      preLoaderRoute: typeof EndListYearMonthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stories/$slug/$num': {
      id: '/stories/$slug/$num'
      path: '/stories/$slug/$num'
      fullPath: '/stories/$slug/$num'
      preLoaderRoute: typeof StoriesSlugNumRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  AddRoute: AddRoute,
  EndingSoonRoute: EndingSoonRoute,
  RecentRoute: RecentRoute,
  SearchRoute: SearchRoute,
  ThingSlugRoute: ThingSlugRoute,
  EndListIndexRoute: EndListIndexRoute,
  StoriesIndexRoute: StoriesIndexRoute,
  EndListYearMonthRoute: EndListYearMonthRoute,
  StoriesSlugNumRoute: StoriesSlugNumRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
